### ISSUE TITLE
[Question] How to subscript?!

### ISSUE THREAD

**Issue by gio-va** [panr/hugo-theme-hello-friend#208]
Hello everyone, I'm new in Hugo/markdown/hello-friend, so thanks in advance for your help.

More than an issue, it's a question!
I'm trying to subscript some text, but I can't found the way.
Do I need to activate the PostType feature? In case, how? And then, how to insert subscript in markdown?

Too much question? Sorry 🙏😄

**Comment by adityatelange** [comment]
add to config the code below
in yml
```yml
markup:
  goldmark:
    renderer:
      unsafe: true
```
in toml
```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
```
you may then use as `CO<sub>2</sub>` => CO<sub>2</sub>

read more: https://gohugo.io/getting-started/configuration-markup/#goldmark
