### ISSUE TITLE
Prism breaks syntax line highlighting

### ISSUE THREAD

**Issue by eddebc** [panr/hugo-theme-hello-friend#220]
Using Hugo's Chroma to parse Markdown with this theme selected, if line highlighting is used, it will not show up until `prism.js` is removed.

Markdown code
~~~
```python {hl_lines=[2]}
import socket
import struct
import sys
```
~~~

With `prism.js`
![bad](https://i.imgur.com/imYP617.png)
  
Without `prism.js`
![good](https://i.imgur.com/iLrHxL0.png)
  
Syntax highlight part of `config.toml`
```toml
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
```

Tried to play with the values `codeFences` and `noClasses`, according to similar issues I found, to no avail.  
I also tried to download a new [`prism.js`](https://prismjs.com) while selecting "Line Highlight" and overwriting the one found in `static/assets` to no avail.
