### ISSUE TITLE
Advice on dark theme logo path?

### ISSUE THREAD

**Issue by codefromthecrypt** [panr/hugo-theme-hello-friend#291]
Thanks for the fantastic project. We use this in https://func-e.io and https://wazero.io

On the latter, we are using a logo in lieu of the blinky. I'm wondering how to specify an alternative svg for when it is in dark theme.. any advice?

Here's how we are specifying the default:
```toml
[params]
  defaultTheme = "light"

[languages]
  [languages.en]
    [languages.en.params.logo]
      logoText = "wazero"
      path = "/img/wazero.svg"
```
