### ISSUE TITLE
Github Page support

### ISSUE THREAD

**Issue by tayjaf** [panr/hugo-theme-hello-friend#327]
Hi!

Love the theme.

I'm trying to set it up but I'm getting a wonky result on gh-pages:
https://tayjaf.github.io/cv/

I'm using the following:
https://gohugo.io/hosting-and-deployment/hosting-on-github/
```
name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```

Any ideas as to what's going on here? Does it require layouts page and setup the html? I've gone through the documentation for hosting but I'm not entirely sure as to why this is occurring. I'm fairly new so apologies if the solution is obvious or simple and something I glossed over.
