### ISSUE TITLE
Reorder menu options?

### ISSUE THREAD

**Issue by da-moo** [panr/hugo-theme-hello-friend#37]
Hello! Thank you very much for making this theme, I absolutely love it! One quick question though, is there a way to change the order of the menu items in the `menu.html` partial? My `config.toml` has the following section for menus:

```toml
  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"

    [[languages.en.menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags"

    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts"
```

But no matter which way I arrange them in the config, they appear in the same order on the generated site. I'm new to hugo so I tried looking at the documentation and I think what I want is the [`.weight`](https://gohugo.io/variables/menus/#menu-entry-variables) property but setting that in each of the menu entries isn't working. Is there something I'm missing?
