### ISSUE TITLE
Multi Language Content doesn't work

### ISSUE THREAD

**Issue by bangau1** [panr/hugo-theme-hello-friend#42]
I've added new language, but it doesn't show any link to another language. I've to manually append my url by the language code first. Is it expected?
I organize my content by folder, something like this:
```text
content
├── english
│   ├── page
│   │   └── about.md
│   └── post
│       ├── 2019-02-24-hello-world.md
└── indonesian
    ├── page
    │   └── about.md
    └── post
        ├── 2019-02-24-hello-world.md
```

And I tried this configuration 
```toml
baseurl = "https://blog.agung.io/"
languageCode = "en"
theme = "hello-friend"
paginate = 5
DefaultContentLanguage = "en"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = true
  showRelatedPosts = true

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
    
# Language Setup
[languages]
  [languages.en]
    title = "Hello Friend"
    subtitle = "A simple theme for Hugo"
    contentDir = "content/english"
    contentTypeName = "post"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [languages.id]
    title = "Hello Friend"
    subtitle = "A simple theme for Hugo"
    contentDir = "content/indonesian"
    contentTypeName = "post"
    

    # [languages.id.params.logo]
    #   logoText = "hello friend"
    #   logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
```

It doesn't show the `Indonesian` as a blog menu. I expect that is shown so the reader can switch the language. 
![Screen Shot 2019-03-10 at 19 38 50](https://user-images.githubusercontent.com/352737/54085129-c1e43c00-436c-11e9-9ce6-746820194ccd.png)

Using `beautifulhugo` theme, it shows this 
![Screen Shot 2019-03-10 at 19 41 39](https://user-images.githubusercontent.com/352737/54085134-cdcffe00-436c-11e9-8d2f-5f90c3ae09d0.png)
