### ISSUE TITLE
Only a few languages are highlighted

### ISSUE THREAD

**Issue by Cigh** [panr/hugo-theme-hello-friend#6]
### Hi!
I love your theme and I want to use if for my personal blog, but I encountered a problem with code highlighting. I've tested some languages and it seems only a few of them are being highlighted correctly.
I have both `pygmentsuseclasses = true` and `pygmentsCodeFences = true` in my config file. 
For example, python and elixir:

![screenshot from 2018-08-30 17-34-26](https://user-images.githubusercontent.com/13978521/44862545-2c5c4700-ac7b-11e8-8d69-45de82ad5416.png)

Is there a way to fix that?

**Comment by panr** [comment]
Hi @Cigh, could you show me your code? Do you use Chroma (default Hugo highlighter) or Prism (a package I added do my theme — but with some basic languages) as a code wrapper?

**Comment by Cigh** [comment]
I've just realized that your theme doesn't use Pygment for highlighting, so `pygmentsuseclasses` and `pygmentsCodeFences` properites are useless here, eh. I didn't change anything in the default configuration, so I guess I'm using Chroma for now.

my **config.toml** 
```
baseurl = "https://example.org/"
languageCode = "en-us"
title = "my blog"
theme = "hello-friend"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"
```
And I'm making code snippets in posts **like that:**
```
```python
x = 1
if x == 1:
    # indented four spaces
    print("x is 1.")
    ...
```
```

```elixir
defmodule Identicon do
  def main(input) do
    input
    |> hash_input
    |> pick_color
    |> build_grid
  end
   ...
```

**Comment by panr** [comment]
@Cigh fixed ;-) I've updated Prism package for many new languages and now you can even copy your code to clipboard ;-)

**Comment by Cigh** [comment]
Looks cool! 👍  Thank you once again and have a good night :)

**Comment by panr** [comment]
Your welcome 🕶 Good night too :-)

**Comment by christianpoveda** [comment]
Hi @panr! Sorry for bringing this thing back but syntax highlighting is not working for me (probably is my fault but I cannot figure it out). Here is my config.toml:
```toml
baseUrl = "https://christianpoveda.github.io/"
languageCode = "en-us"
title = "(λx.t)"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "A blog about mischief, mayhem, type systems and soap"

[params.logo]
  logoText = "(λx.t)"

[menu]
  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/christian_poved"
  [[menu.main]]
    identifier = "github"
    name = "Github"
url = "https://github.com/christianpoveda"
```
