### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by jeremejazz** [panr/hugo-theme-hello-friend#68]
Just a suggestion, I think it would be also great to have an optional Table of Contents for single pages since hugo already has a built-in [page variable](https://gohugo.io/content-management/toc/) for that.  :smile:

**Comment by jeremejazz** [comment]
Quick work to this I override the `layouts/_default/single.html` and added the following lines before .post-content

```html
    {{ if and (isset .Params "toc") .Params.toc }}
    <details class="toc">
      <summary>Table of Contents</summary>
      {{ .TableOfContents }}
    </details>
  {{ end }}
```

Then add a css block 

```css
.toc ul > li {
    display: block;
    margin-left: -20px;
}
```
Though this still has a problem with responsiveness especially by with the negative margin. There might be a better approach to this though like media queries or not using the margin :rofl:  :smile_cat:

**Comment by thomasjsn** [comment]
This what I do;

## Shortcode
```html
<details class="entry-toc">
  <summary>
    <span>
      Table of contents
    </span>
  </summary>
  {{ .Page.TableOfContents }}
</details>
```

## Style
```css
.entry-toc nav > ul {
    margin: 0;
}
.entry-toc ul {
    list-style: none;
}
```

I prefer a shortcode, that way I can add it where it makes sense. And no need to override anything.
