### ISSUE TITLE
Is it possible to wrap lines in code blocks?

### ISSUE THREAD

**Issue by MasterGroosha** [panr/hugo-theme-hello-friend#85]
Currently code blocks show horizontal scrollbars for long lines.
Is it possible to enable wrapping instead?
![изображение](https://user-images.githubusercontent.com/2780044/63011152-6aed1080-be90-11e9-892c-ef9e9f53f903.png)

**Comment by panr** [comment]
From docs: `If you have to override some of the styles, you can do this easily by adding static/style.css in your root directory and point things you want to change.` so you can override this.

Also I think I can make these scrollbars prettier (soon) ;-)

**Comment by MasterGroosha** [comment]
Solved by adding 
```css
code[class*="language-"],
pre[class*="language-"] {
     white-space: pre-wrap;
}
```
to **static/style.css**
